version: '3.4'
services:
  outserv-lambda:
    build:
      context: .
      target: build
      args:
        nodeEnv: development
    ports:
      - "8686:8686"
    depends_on:
      - outserv
    environment:
      DGRAPH_URL: http://outserv:8080
      INTEGRATION_TEST: "true"
  outserv:
    image: outcaste/outserv:latest
    command: outserv alpha --my=outserv:7080 --zero=zero:5080 --logtostderr -v=2
  zero:
    image: outcaste/outserv:latest
    command: outserv zero --my=zero:5080 --raft 'idx=1' --logtostderr -v=2
